### ISSUE TITLE
`TODO` for v0.1.0 

### ISSUE THREAD

**Issue by WSH032** [WSH032/aria2-wheel#18]
- [ ] When building, perform hash verification checks on the downloaded aria2 artifacts
- [ ] Adopt [cibuildwheel](https://[cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/).readthedocs.io/en/stable/) for more accurate testing and building
- [ ] Fix code coverage inconsistency between Unix and Windows

--- 

TODO for v1.0.0
- [ ] macos support
